---
title: "Support a New Relational Database Management System"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{add_a_database_module}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

Database connections in ReviewR are created with the help of the [DBI Package](https://db.rstudio.com/dbi/) from RStudio. This allows ReviewR to interact with any database supported by DBI. A full list of compatable database back-ends[*](#dplyr-support) can be found [here](https://db.rstudio.com/databases/). 

The DBI package is responsible for creating a DBI connection object. This connection object defines the type of database, connection information (ip, port, etc.), and the user and any associated credentials. These connection objects can then be used to create connections to tables within the database.

ReviewR facilitates these DBI connections through the use of  [Shiny Modules](https://mastering-shiny.org/scaling-modules.html). Modules are a way to make a complex Shiny application more manageable. They help compartmentalize code, with each module developed for a specific purpose. At their core, modules take user inputs that are defined in a UI function, process the user inputs in a server function and return an output. Each module operates in its own namespace, which means that shiny modules are portable, meaning they can be used in other applications and/or reusable within the same application. 


<a name="dplyr-support"></a>
*\*Note: Supported Databases must also have [dplyr](https://db.rstudio.com/dplyr) support.*

## Developing a Database Module for ReviewR