#' user_table
#'
#' @param table_map A reactive tibble, generated by the data_model_detection module containing user database tables and fields mapped to the determined CDM
#' @param connection_info A reactive DBI connection object that is created through user interaction with the Setup Tab
#' @param desired_cdm_table In the desired CDM, which table do you want?
#'
#' @return tbl(connection_info, user_table) the user table that corresponds to the omop table you want
#' @export
#'
#' @examples
#' user_table(table_map = table_map, connection_info = db_connection, 'person', db_schema_name = 'cdm')
user_table <- function(table_map, connection_info, desired_cdm_table, db_schema_name) {
  req(table_map(), connection_info())
  table_name <- table_map()$model_match[[1]] %>% 
    filter(table == desired_cdm_table) %>% 
    distinct(table, .keep_all = T) %>% 
    select(user_database_table) %>% 
    pluck(1)
  if (is.na(db_schema_name) | is.null(db_schema_name) | db_schema_name() == '') {
    tbl(src = connection_info(), table_name)
  }
  else {
    tbl(src = connection_info(), in_schema(db_schema_name(), table_name))
  }
}

#' user_field
#'
#' @param table_map A reactive tibble, generated by the data_model_detection module containing user database tables and fields mapped to the determined CDM
#' @param desired_cdm_table In the OMOP CDM, which table do you want?
#' @param desired_cdm_field In the OMOP CDM, which field do you want?
#'
#' @return character object containing the user database field pertaining to the omop field you want, from the omop table specified
#' @export
#'
#' @examples
#' user_field(table_map = table_map, desired_user_table = 'person', desired_user_field = 'person_id')
user_field <- function(table_map, desired_cdm_table, desired_cdm_field){
  req(table_map())
  table_map()$model_match[[1]] %>% 
    filter(table == desired_cdm_table & field == desired_cdm_field) %>% 
    select(user_fields) %>% 
    pluck(1)
}
