#' user_table
#'
#' @param table_map A reactive tibble, generated by the data_model_detection module containing user database tables and fields mapped to the determined CDM
#' @param connection_info A reactive DBI connection object that is created through user interaction with the Setup Tab
#' @param desired_omop_table In the OMOP CDM, which table do you want?
#'
#' @return tbl(connection_info, user_table) the user table that corresponds to the omop table you want
#' @export
#'
#' @examples
#' user_table(table_map = table_map, connection_info = db_connection, 'person')
user_table <- function(table_map, connection_info, desired_omop_table) {
  req(table_map(), connection_info())
  table_name <- table_map()$model_match[[1]] %>% 
    filter(table == desired_omop_table) %>% 
    distinct(table, .keep_all = T) %>% 
    select(user_database_table) %>% 
    pluck(1)
  tbl(src = connection_info(), table_name)
}

#' user_field
#'
#' @param table_map A reactive tibble, generated by the data_model_detection module containing user database tables and fields mapped to the determined CDM
#' @param desired_omop_table In the OMOP CDM, which table do you want?
#' @param desired_omop_field In the OMOP CDM, which field do you want?
#'
#' @return character object containing the user database field pertaining to the omop field you want, from the omop table specified
#' @export
#'
#' @examples
#' user_field(table_map = table_map, desired_omop_table = 'person', desired_omop_field = 'person_id')
user_field <- function(table_map, desired_omop_table, desired_omop_field){
  req(table_map())
  table_map()$model_match[[1]] %>% 
    filter(table == desired_omop_table & field == desired_omop_field) %>% 
    select(user_fields) %>% 
    pluck(1)
}
