DROP INDEX IF EXISTS chartevents_1_subject_hadm;
CREATE INDEX chartevents_1_subject_hadm ON chartevents_1 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_2_subject_hadm;
CREATE INDEX chartevents_2_subject_hadm ON chartevents_2 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_3_subject_hadm;
CREATE INDEX chartevents_3_subject_hadm ON chartevents_3 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_4_subject_hadm;
CREATE INDEX chartevents_4_subject_hadm ON chartevents_4 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_5_subject_hadm;
CREATE INDEX chartevents_5_subject_hadm ON chartevents_5 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_6_subject_hadm;
CREATE INDEX chartevents_6_subject_hadm ON chartevents_6 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_7_subject_hadm;
CREATE INDEX chartevents_7_subject_hadm ON chartevents_7 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_8_subject_hadm;
CREATE INDEX chartevents_8_subject_hadm ON chartevents_8 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_9_subject_hadm;
CREATE INDEX chartevents_9_subject_hadm ON chartevents_9 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_10_subject_hadm;
CREATE INDEX chartevents_10_subject_hadm ON chartevents_10 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_11_subject_hadm;
CREATE INDEX chartevents_11_subject_hadm ON chartevents_11 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_12_subject_hadm;
CREATE INDEX chartevents_12_subject_hadm ON chartevents_12 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_13_subject_hadm;
CREATE INDEX chartevents_13_subject_hadm ON chartevents_13 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_14_subject_hadm;
CREATE INDEX chartevents_14_subject_hadm ON chartevents_14 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_15_subject_hadm;
CREATE INDEX chartevents_15_subject_hadm ON chartevents_15 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_16_subject_hadm;
CREATE INDEX chartevents_16_subject_hadm ON chartevents_16 (subject_id, hadm_id);
DROP INDEX IF EXISTS chartevents_17_subject_hadm;
CREATE INDEX chartevents_17_subject_hadm ON chartevents_17 (subject_id, hadm_id);
